wip4
GPUtrainAIcontroller.py
cuda
Traceback (most recent call last):
  File "/home/curt/dev/python/Python_Fifteen_Game/GPUtrainAIcontroller.py", line 30, in <module>
    action = torch.argmax(q_table[state_to_index(state_torch)]).item()  # Exploit
  File "/home/curt/.local/lib/python3.8/site-packages/numba/core/dispatcher.py", line 468, in _compile_for_args
    error_rewrite(e, 'typing')
  File "/home/curt/.local/lib/python3.8/site-packages/numba/core/dispatcher.py", line 409, in error_rewrite
    raise e.with_traceback(None)
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
non-precise type pyobject
During: typing of argument at /home/curt/dev/python/Python_Fifteen_Game/tile_game_env.py (82)

File "tile_game_env.py", line 82:
def state_to_index(state):
    index = 0
    ^

This error may have been caused by the following argument(s):
- argument 0: Cannot determine Numba type of <class 'torch.Tensor'>